export const chats = [
  {
    chat_id: "peer_private_chat1",
    peer_private: true,
    participants: ["user1", "user2"],
    messages: ["message1", "message2", "message3"],
    group_name: null,
    group_profile: null,
  },
  {
    chat_id: "peer_private_chat2",
    peer_private: true,
    participants: ["user1", "user3"],
    messages: ["message4", "message5"],
    group_name: null,
    group_profile: null,
  },
  {
    chat_id: "group_chat1",
    peer_private: false,
    admin: "user1",
    participants: ["user1", "user2", "user5", "user6"],
    messages: ["message9", "message10"],
    group_name: "classmates",
    group_profile: "group_chat1.png",
  },
  {
    chat_id: "group_chat2",
    peer_private: false,
    admin: "user3",
    participants: ["user1", "user5", "user7", "user10"],
    messages: ["message11"],
    group_name: "Gamers",
    group_profile: "group_chat2.png",
  },
  {
    chat_id: "group_chat3",
    peer_private: false,
    admin: "user5",
    participants: ["user1", "user6", "user7", "user10"],
    messages: ["message12", "message13", "message14"],
    group_name: "freedom!",
    group_profile: "group_chat3.png",
  },
  {
    chat_id: "peer_private_chat5",
    peer_private: true,
    participants: ["user1", "user6"],
    messages: ["message17"],
    group_name: null,
    group_profile: null,
  },
  {
    chat_id: "peer_private_chat7",
    peer_private: true,
    participants: ["user1", "user10"],
    messages: ["message21", "message22", "message23"],
    group_name: null,
    group_profile: null,
  },
  {
    chat_id: "peer_private_chat9",
    peer_private: true,
    participants: ["user1", "user7"],
    messages: ["message26", "message27"],
    group_name: null,
    group_profile: null,
  },
  {
    chat_id: "peer_private_chat9",
    peer_private: true,
    participants: ["user1", "user8"],
    messages: ["message15", "message14"],
    group_name: null,
    group_profile: null,
  },
];
